SettingsButton:

<SettingsButton>:
        text: "Settings"                 # Label
        font_size: '32dp'               # Font Size
        text_size: None, self.height    # Needed to Align text
        valign: 'bottom'                # Align Text to the bottom of the button
        color: 0,0,0,1                  # Text Color in RGBA
        # background_normal: background image
        # background_down: Button pushed image

